let itemsData = [
  {
    id: "asdas",
    name: "Rose red",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/1.jpg",
  },
  {
    id: "dsds",
    name: "Purple flower",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/2.jpg",
  },
  {
    id: "qwewqwe",
    name: "Rose bicolored",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/3.jpg",
  },
  {
    id: "ewqwewq",
    name: "Liver flower",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/4.jpg",
  },
  {
    id: "wqweqwe",
    name: "Lotus flower",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/5.jpg",
  },
  {
    id: "dfgdfg",
    name: "Marigold flower",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/6.jpg",
  },
  {
    id: "gfdgfd7",
    name: "Water lili flower",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/7.jpg",
  },
  {
    id: "cvbcvb8",
    name: "Blue flower",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/8.jpg",
  },
  {
    id: "bvcbc",
    name: "Cosmos flower",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/9.jpg",
  },
  {
    id: "yrtyrty",
    name: "Sunflower",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/10.jpg",
  },
  {
    id: "rtyrty",
    name: "Bell flower",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/11.jpg",
  },
  {
    id: "hjkhjk",
    name: "Dahlia flower",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "pictures/12.jpg",
  },
];
